import { makeOpenAICompatProvider, DynamicOpenAICompatProvider } from './openai_compat.js';
import { OllamaProvider } from './ollama.js';
import { OpenAIProvider } from './openai.js';
import { AnthropicProvider } from './anthropic.js';
import { MiniMaxProvider } from './minimax.js';
import { ClaudeCodeProvider } from './claude-code.js';

export const PROVIDER_REGISTRY = [
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Local models — no API key required',
    icon: '🦙',
    requiresKey: false,
    keyHint: '',
    Class: OllamaProvider,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude 3.5 Sonnet, Claude 3 Opus, Haiku',
    icon: '🧠',
    requiresKey: true,
    keyHint: 'sk-ant-...',
    Class: AnthropicProvider,
  },
  {
    id: 'claude-code',
    name: 'Claude (subscription)',
    description: 'Claude via your Anthropic account — uses the Claude Code login, no API key',
    icon: '🔐',
    requiresKey: false,
    keyHint: '',
    Class: ClaudeCodeProvider,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o, GPT-4 Turbo, o1, o3',
    icon: '🤖',
    requiresKey: true,
    keyHint: 'sk-...',
    Class: OpenAIProvider,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: '300+ models — Claude, GPT, Gemini, Llama, DeepSeek…',
    icon: '🔀',
    requiresKey: true,
    keyHint: 'sk-or-...',
    Class: makeOpenAICompatProvider('openrouter', 'https://openrouter.ai/api/v1'),
  },
  {
    id: 'openprovider',
    name: 'OpenProvider',
    description: 'Community OpenAI-compatible endpoint (Mimika)',
    icon: '🛰️',
    requiresKey: true,
    keyHint: 'user API key',
    Class: makeOpenAICompatProvider('openprovider', 'https://openprovider.mimika.in/v1'),
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    description: 'Llama 3.1/3.3, Mistral, Nemotron, DeepSeek via NVIDIA cloud',
    icon: '🎮',
    requiresKey: true,
    keyHint: 'nvapi-...',
    Class: makeOpenAICompatProvider('nvidia', 'https://integrate.api.nvidia.com/v1'),
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast inference — Llama, Mixtral, Gemma, DeepSeek',
    icon: '⚡',
    requiresKey: true,
    keyHint: 'gsk_...',
    Class: makeOpenAICompatProvider('groq', 'https://api.groq.com/openai/v1'),
  },
  {
    id: 'google',
    name: 'Google Gemini',
    description: 'Gemini 2.0, 1.5 Pro/Flash via AI Studio',
    icon: '💎',
    requiresKey: true,
    keyHint: 'AIza...',
    Class: makeOpenAICompatProvider('google', 'https://generativelanguage.googleapis.com/v1beta/openai'),
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral Large, Codestral, Pixtral, Ministral',
    icon: '🌀',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('mistral', 'https://api.mistral.ai/v1'),
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'Open models — Llama, Mistral, Qwen, DeepSeek, Gemma',
    icon: '🤝',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('together', 'https://api.together.xyz/v1'),
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    description: 'Ultra-fast Llama 3.1/3.3 on Cerebras hardware',
    icon: '🧬',
    requiresKey: true,
    keyHint: 'csk-...',
    Class: makeOpenAICompatProvider('cerebras', 'https://api.cerebras.ai/v1'),
  },
  // ── Western providers ────────────────────────────────────────────────────
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek-V3, DeepSeek-R1 — top open reasoning models',
    icon: '🐋',
    requiresKey: true,
    keyHint: 'sk-...',
    Class: makeOpenAICompatProvider('deepseek', 'https://api.deepseek.com/v1'),
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    description: 'Grok-3, Grok-3 Mini, Grok-2 — from Elon Musk\'s xAI',
    icon: '✖️',
    requiresKey: true,
    keyHint: 'xai-...',
    Class: makeOpenAICompatProvider('xai', 'https://api.x.ai/v1'),
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Sonar Pro, Sonar Reasoning — web-grounded search models',
    icon: '🔍',
    requiresKey: true,
    keyHint: 'pplx-...',
    Class: makeOpenAICompatProvider('perplexity', 'https://api.perplexity.ai'),
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Fast inference — Llama, DeepSeek-R1, Qwen, Mixtral',
    icon: '🎆',
    requiresKey: true,
    keyHint: 'fw_...',
    Class: makeOpenAICompatProvider('fireworks', 'https://api.fireworks.ai/inference/v1'),
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    description: 'Llama 3.1 405B, DeepSeek-R1-671B — fastest large models',
    icon: '🏎️',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('sambanova', 'https://api.sambanova.ai/v1'),
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    description: 'Llama, DeepSeek, Qwen — affordable GPU inference',
    icon: '🔷',
    requiresKey: true,
    keyHint: 'sk-...',
    Class: makeOpenAICompatProvider('hyperbolic', 'https://api.hyperbolic.xyz/v1'),
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command R+, Command A — enterprise RAG & reasoning',
    icon: '🌊',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('cohere', 'https://api.cohere.com/compatibility/v1'),
  },
  {
    id: 'ai21',
    name: 'AI21 Labs',
    description: 'Jamba 2.0, Jamba 1.5 — long-context SSM hybrid models',
    icon: '🔬',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('ai21', 'https://api.ai21.com/studio/v1'),
  },
  {
    id: 'novita',
    name: 'Novita AI',
    description: 'Affordable open models — Llama, Qwen, DeepSeek, Mistral',
    icon: '🌟',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('novita', 'https://api.novita.ai/v1'),
  },
  {
    id: 'upstage',
    name: 'Upstage',
    description: 'Solar Pro, Solar Mini — Korean frontier models',
    icon: '☀️',
    requiresKey: true,
    keyHint: 'up-...',
    Class: makeOpenAICompatProvider('upstage', 'https://api.upstage.ai/v1'),
  },
  {
    id: 'lepton',
    name: 'Lepton AI',
    description: 'Llama, DeepSeek, Qwen — serverless GPU inference',
    icon: '⚛️',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('lepton', 'https://api.lepton.ai/api/v1'),
  },
  // ── Chinese providers ────────────────────────────────────────────────────
  {
    id: 'minimax',
    name: 'MiniMax (Token Plan)',
    description: 'MiniMax-M3 — Coding Plan subscription',
    icon: '🎯',
    requiresKey: true,
    keyHint: 'Token Plan API key',
    Class: MiniMaxProvider,
  },
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    description: 'Kimi-K2, Moonshot-v1 — ultra long context models',
    icon: '🌙',
    requiresKey: true,
    keyHint: 'sk-...',
    Class: makeOpenAICompatProvider('moonshot', 'https://api.moonshot.cn/v1'),
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    description: 'GLM-4, GLM-4-Air, GLM-4-Flash — Chinese enterprise models',
    icon: '🧩',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('zhipu', 'https://open.bigmodel.cn/api/paas/v4'),
  },
  {
    id: 'yi',
    name: '01.AI (Yi)',
    description: 'Yi-Lightning, Yi-Large, Yi-Medium — efficient 01.AI models',
    icon: '⭕',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('yi', 'https://api.lingyiwanwu.com/v1'),
  },
  {
    id: 'qwen',
    name: 'Alibaba (Qwen)',
    description: 'Qwen-Plus, Qwen-Turbo, Qwen2.5-72B — Alibaba DashScope',
    icon: '☁️',
    requiresKey: true,
    keyHint: 'sk-...',
    Class: makeOpenAICompatProvider('qwen', 'https://dashscope.aliyuncs.com/compatible-mode/v1'),
  },
  {
    id: 'baichuan',
    name: 'Baichuan AI',
    description: 'Baichuan4, Baichuan3-Turbo — Chinese frontier models',
    icon: '🏔️',
    requiresKey: true,
    keyHint: 'sk-...',
    Class: makeOpenAICompatProvider('baichuan', 'https://api.baichuan-ai.com/v1'),
  },
  {
    id: 'stepfun',
    name: 'Stepfun (阶跃星辰)',
    description: 'Step-2, Step-1V — multimodal Chinese frontier models',
    icon: '👣',
    requiresKey: true,
    keyHint: '...',
    Class: makeOpenAICompatProvider('stepfun', 'https://api.stepfun.com/v1'),
  },
  {
    id: 'z-ai',
    name: 'Z-AI',
    description: 'Z-AI models — OpenAI-compatible Chinese AI platform',
    icon: '⚡',
    requiresKey: true,
    keyHint: 'sk-...',
    Class: makeOpenAICompatProvider('z-ai', 'https://api.z.ai/v1'),
  },
  {
    id: 'openai-compat',
    name: 'OpenAI Compatible',
    description: 'Any OpenAI-compatible endpoint — vLLM, LM Studio, NVIDIA NIM, custom…',
    icon: '🔧',
    requiresKey: true,
    requiresBaseUrl: true,
    keyHint: 'sk-... or nvapi-... or your key',
    baseUrlHint: 'https://integrate.api.nvidia.com/v1',
    modelHint: 'e.g. your-model-id',
    Class: DynamicOpenAICompatProvider,
  },
];

export function getProviderClass(id) {
  const entry = PROVIDER_REGISTRY.find(p => p.id === id);
  return entry?.Class || null;
}

export function getProviderMeta(id) {
  return PROVIDER_REGISTRY.find(p => p.id === id) || null;
}
